[phases.setup]
nixFile = "shell.nix"  # Points to your custom shell.nix file

[phases.install]
cmds = ['pip install -r requirements.txt']  # This will now work with pip from nix

[start]
cmd = 'gunicorn app:app'
